server:
  port: 8080



spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: customer_service
    password: password
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: none


  flyway:
    enabled: true
    create-schemas: false







logging:
  level:
    org.springframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: customer-service
